import type { Metadata } from "next";
import "./globals.css";
import { Fredoka , Montserrat } from "next/font/google";
import Providers from "@/app/Providers";
import Footer from "@/component/Footer";

const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-fredoka",
});
const monserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-fredoka",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fredoka.variable} ${monserrat.variable}` }
      suppressHydrationWarning>
      <Providers>{children}
        <Footer/>
      </Providers>
      
      </body>
    </html>
  );
}
