import type { Metadata } from "next";
import "./globals.css";
import { Fredoka , Montserrat } from "next/font/google";
import Providers from "@/app/Providers";

const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-fredoka",
});
const monserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-fredoka",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fredoka.variable} ${monserrat.variable}`}
      >
      <Providers>{children}</Providers>
      </body>
    </html>
  );
}
